<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "space_base"
 *
 * Auto generated by Extension Builder 2019-03-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Space Base',
    'description' => 'Default Template Extension',
    'category' => 'templates',
    'author' => '',
    'author_email' => '',
    'state' => 'stable',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '9.5',
    'constraints' => [
        'depends' => [
            'typo3' => '9.0.0-9.99.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
